### ISSUE TITLE
val_loss_epoch

### ISSUE THREAD

**Issue by P16101150** [Kemo-Huang/JMODT#9]
Traceback (most recent call last):
File "tools/train.py", line 164, in
main()
File "tools/train.py", line 157, in main
val_loader
File "/home/my_com/virtualenv/JMODT/jmodt/utils/train_utils.py", line 198, in train
prev_val_loss = val_loss_epoch

How can i solve it?

**Comment by zkp0113** [comment]
Excuse me，I meet same problems.
No.1 ”UnboundLocalError: local variable 'val_loss_epoch' referenced before assignment“；
For this problem I change some code then the problem fixed，but it comes new problem that same with this.

No.2 “best_model.path” is not update.

对不起，我也遇到同样的问题。
第1条问 “UnboundLocalError:赋值前引用的局部变量‘val_loss_epoch’”；对于这个问题，我更改了一些代码，然后问题得到了解决，但随之而来的是新问题。
第2条 “best_model.path”未更新。

**Comment by zkp0113** [comment]
> Traceback (most recent call last): File "tools/train.py", line 164, in main() File "tools/train.py", line 157, in main val_loader File "/home/my_com/virtualenv/JMODT/jmodt/utils/train_utils.py", line 198, in train prev_val_loss = val_loss_epoch
> 
> How can i solve it?

Nice to meet u，can u help me to how to fix the problem？
